[supervisord]
nodaemon = true

[program:sshd]
priority = 1
command = /usr/sbin/sshd -D

[program:influxdb]
priority = 2
command = bash -c "/etc/init.d/influxdb start && sleep 5"

[program:chronograf]
priority = 3
command = bash -c "chronograf && sleep 5"

[program:grafana]
priority = 4
command = bash -c "cd /usr/share/grafana && /usr/sbin/grafana-server --config /etc/grafana/grafana.ini"
